using Spas.Sdk.Metadata.Attributes;
using Spas.Sdk.Metadata.Schema;

namespace Spas.Sdk.Metadata.Tests;

public class SchemaGeneratorTests
{
    [Fact]
    public async Task GenerateSchemasFromAssembly_WithCommandAttribute_GeneratesSchema()
    {
        // Arrange
        var generator = new SchemaGenerator();
        var assembly = typeof(TestCommandForSchema).Assembly;

        // Act
        var schemas = await generator.GenerateSchemasFromAssemblyAsync(assembly);

        // Assert
        Assert.Contains("schemas/endpoints/test-command.schema.json", schemas.Keys);
        var schema = schemas["schemas/endpoints/test-command.schema.json"] as string;
        Assert.NotNull(schema);
        Assert.Contains("\"type\":", schema);
        Assert.Contains("\"properties\":", schema);
        // Schemas use camelCase to match runtime JSON serialization
        Assert.Contains("\"commandId\":", schema);
        Assert.Contains("\"data\":", schema);
    }

    [Fact]
    public async Task GenerateSchemasFromAssembly_WithQueryAttribute_GeneratesSchema()
    {
        // Arrange
        var generator = new SchemaGenerator();
        var assembly = typeof(TestQueryForSchema).Assembly;

        // Act
        var schemas = await generator.GenerateSchemasFromAssemblyAsync(assembly);

        // Assert
        Assert.Contains("schemas/endpoints/test-query.schema.json", schemas.Keys);
        var schema = schemas["schemas/endpoints/test-query.schema.json"] as string;
        Assert.NotNull(schema);
        Assert.Contains("\"type\":", schema);
        // Schemas use camelCase to match runtime JSON serialization
        Assert.Contains("\"queryId\":", schema);
    }

    [Fact]
    public async Task GenerateSchemasFromAssembly_WithEventAttribute_GeneratesSchema()
    {
        // Arrange
        var generator = new SchemaGenerator();
        var assembly = typeof(TestEventForSchema).Assembly;

        // Act
        var schemas = await generator.GenerateSchemasFromAssemblyAsync(assembly);

        // Assert
        Assert.Contains("schemas/events/test-event.schema.json", schemas.Keys);
        var schema = schemas["schemas/events/test-event.schema.json"] as string;
        Assert.NotNull(schema);
        Assert.Contains("\"type\":", schema);
        // Schemas use camelCase to match runtime JSON serialization
        Assert.Contains("\"eventId\":", schema);
        Assert.Contains("\"timestamp\":", schema);
    }

    [Fact]
    public async Task GenerateSchemasFromAssembly_WithMultipleAttributes_GeneratesAllSchemas()
    {
        // Arrange
        var generator = new SchemaGenerator();
        var assembly = typeof(TestCommandForSchema).Assembly;

        // Act
        var schemas = await generator.GenerateSchemasFromAssemblyAsync(assembly);

        // Assert
        Assert.True(schemas.Count >= 3, $"Expected at least 3 schemas, found {schemas.Count}");
        Assert.Contains("schemas/endpoints/test-command.schema.json", schemas.Keys);
        Assert.Contains("schemas/endpoints/test-query.schema.json", schemas.Keys);
        Assert.Contains("schemas/events/test-event.schema.json", schemas.Keys);
    }

    [Fact]
    public async Task GenerateSchemaAsync_ForSpecificType_GeneratesValidSchema()
    {
        // Arrange
        var generator = new SchemaGenerator();

        // Act
        var schema = await generator.GenerateSchemaAsync(typeof(TestCommandForSchema)) as string;

        // Assert
        Assert.NotNull(schema);
        Assert.Contains("\"$schema\":", schema);
        Assert.Contains("\"type\":", schema);
        Assert.Contains("\"properties\":", schema);
        // Schemas use camelCase to match runtime JSON serialization
        Assert.Contains("\"commandId\":", schema);
    }

    [Fact]
    public async Task GenerateSchemasFromAssembly_WithAutoGeneratedSchema_IncludesType()
    {
        // Arrange
        var generator = new SchemaGenerator();
        var assembly = typeof(TestCommandWithAutoSchema).Assembly;

        // Act
        var schemas = await generator.GenerateSchemasFromAssemblyAsync(assembly);

        // Assert - should contain auto-generated schema
        Assert.Contains("schemas/endpoints/test-with-auto-schema.schema.json", schemas.Keys);
    }
}

// Test types for schema generation unit tests
public record TestCommandForSchema(Guid CommandId, string Data);

public record TestQueryForSchema(string QueryId, int PageSize);

[SpasEvent("TestEvent", "1.0", EventType = "com.test.event")]
public record TestEventForSchema(Guid EventId, DateTime Timestamp, string Message);

public record TestCommandWithAutoSchema(Guid Id);
