/**
 * Archive reader service for extracting spas.json from ZIP files
 */

import AdmZip from 'adm-zip';
import { createCliError, ErrorCode, type ServiceIdentity } from '../types.js';

export class ArchiveReader {
  /**
   * Extract spas.json from a ZIP archive and return service identity
   *
   * @param archiveBuffer - ZIP file contents as Buffer
   * @returns Service identity extracted from spas.json
   * @throws CliError if spas.json is missing or invalid
   */
  async extractIdentity(archiveBuffer: Buffer): Promise<ServiceIdentity> {
    try {
      const zip = new AdmZip(archiveBuffer);
      const spasJsonEntry = zip.getEntry('spas.json');

      if (!spasJsonEntry) {
        throw createCliError(
          ErrorCode.ARCHIVE_INVALID,
          'Archive does not contain spas.json',
          'Ensure the archive was generated by a SPAS SDK'
        );
      }

      const spasJsonContent = spasJsonEntry.getData().toString('utf8');
      const spasJson = JSON.parse(spasJsonContent);

      // Validate required fields
      if (!spasJson.id || !spasJson.version) {
        throw createCliError(
          ErrorCode.ARCHIVE_INVALID,
          'spas.json is missing required fields (id, version)',
          'Check that the service metadata is properly configured'
        );
      }

      return {
        id: spasJson.id,
        name: spasJson.name,
        version: spasJson.version,
        schemaVersion: spasJson.schemaVersion,
        boundedContext: spasJson.boundedContext,
      };
    } catch (error) {
      if ((error as any).code) {
        // Already a CliError
        throw error;
      }

      throw createCliError(
        ErrorCode.ARCHIVE_INVALID,
        'Failed to parse JSON in spas.json',
        'Ensure the file contains valid JSON',
        error
      );
    }
  }

  /**
   * List all schema files in the archive
   *
   * @param archiveBuffer - ZIP file contents as Buffer
   * @returns Array of schema file paths
   */
  listSchemas(archiveBuffer: Buffer): string[] {
    try {
      const zip = new AdmZip(archiveBuffer);
      const entries = zip.getEntries();

      return entries
        .filter(entry => entry.entryName.startsWith('schemas/') && entry.entryName.endsWith('.schema.json'))
        .map(entry => entry.entryName);
    } catch (error) {
      return [];
    }
  }
}
