/**
 * Sidecar Configuration Types
 * 
 * These types define the schema for sidecar configuration files
 * generated by spas-compose choreography deploy.
 * 
 * @see spec.md for functional requirements
 * @see data-model.md for entity relationships
 */

/**
 * Complete sidecar configuration for a single service.
 * Generated as config.{serviceName}.json
 */
export interface SidecarConfig {
  /** Event subscriptions and command handlers */
  inbound: InboundEntry[];
  /** Event publication configurations */
  outbound: OutboundEntry[];
}

/**
 * Configuration for receiving events or commands.
 * Sidecar subscribes to topic/command and invokes service HTTP endpoint.
 */
export interface InboundEntry {
  /** Type of inbound message */
  kind: "event" | "command";
  /** Topic name (required when kind="event") */
  topic?: string;
  /** Command name (required when kind="command") */
  command?: string;
  /** Path to JSONata transformation file, relative to sidecar /app/transformations mount */
  transform?: string;
  /** HTTP endpoint path on the service to invoke */
  invokeEndpoint: string;
}

/**
 * Configuration for publishing events.
 * Sidecar transforms and publishes to topic.
 */
export interface OutboundEntry {
  /** Topic name for published events */
  topic: string;
  /** Path to JSONata transformation file, relative to sidecar /app/transformations mount */
  transform?: string;
}

/**
 * Result of config generation process
 */
export interface ConfigGeneratorResult {
  /** Whether generation succeeded */
  success: boolean;
  /** Service name → config mapping (populated on success) */
  configs: Record<string, SidecarConfig>;
  /** List of errors (populated on failure) */
  errors: ConfigError[];
  /** Summary for CLI output */
  summary: ConfigSummary;
}

/**
 * Error details for generation failures
 */
export interface ConfigError {
  /** Service name where error occurred */
  service: string;
  /** Human-readable error message */
  message: string;
  /** Error category */
  type: "MISSING_TRANSFORM" | "INVALID_PATH" | "INVALID_CHOREOGRAPHY";
}

/**
 * Summary of generated configs for CLI output
 */
export interface ConfigSummary {
  /** Total number of config files generated */
  totalConfigs: number;
  /** Services with their entry counts */
  services: ServiceSummary[];
}

/**
 * Summary for a single service
 */
export interface ServiceSummary {
  /** Service name */
  name: string;
  /** Number of inbound entries */
  inboundCount: number;
  /** Number of outbound entries */
  outboundCount: number;
}
