<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Spas.Sdk.Core\Spas.Sdk.Core.csproj" />
    <ProjectReference Include="..\Spas.Sdk.Metadata\Spas.Sdk.Metadata.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
