apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: ""
---
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: order-events
spec:
  pubsubname: pubsub
  topic: orders
  route: /events/order
  metadata:
    rawPayload: "false"
